### ISSUE TITLE
"stylemark@0.6.2" is missing a bundled dependency "rfr"

### ISSUE THREAD

**Issue by FlorianKoerner** [nextbigsoundinc/stylemark#17]
Yarn gives me a warning about stylemark since the latest version.

    warning "stylemark@0.6.2" is missing a bundled dependency "rfr". This should be reported to the package maintainer.

**Comment by mpetrovich** [comment]
Whoops, my fault—I messed up the release. [v0.6.3](https://github.com/nextbigsoundinc/stylemark/releases/tag/v0.6.3) fixes this.
