### ISSUE TITLE
Iframe doesn't load in Windows environment

### ISSUE THREAD

**Issue by jenshedqvist** [nextbigsoundinc/stylemark#19]
I've done some test on running the Stylemark server with `npm run start` in Windows 10 and Windows 7 and it looks fine in the terminal and the console (except IE which chokes on `startsWith`), but the iframe won't load in any browser (Chrome, Firefox, IE etc). Everything else seems to be running fine. The entire `div.i-example` is missing.

**Comment by Atanas-F-Nikolov** [comment]
The Stylemark markdown parser doesn't handle Windows-style line endings (CRLF, 0x0D 0x0A) correctly, so the example blocks do not work on Windows if you have CRLF line endings in the markdown files. If you change the .md files to be encoded with LF only, it works. However, if you use git on Windows it usually defaults to auto-translating LF to CRLF on checkout, so to actually get the fix to stick you'll probably have to say `git config core.autocrlf false`, or it'll get converted back to CRLF.

**Comment by SuneRadich** [comment]
Is this something that will be fixed. When working on projects with many developers, all on Windows computers, its not really an options to not use CRLF.

**Comment by mpetrovich** [comment]
Fixed in [v0.6.6](https://github.com/nextbigsoundinc/stylemark/releases/tag/v0.6.6)
