### ISSUE TITLE
External sources

### ISSUE THREAD

**Issue by ckrack** [nextbigsoundinc/stylemark#3]
I'd love to be able to reference external examples.

I dislike writing ``` all the time and would love to keep my examples in real files, so they are syntax highlighted.

There could be an import directive or a naming scheme to find the files.
```
#include example/*
```

Equally named files could be grouped, just as in the markdown.
```
./example/hello.js
./example/hello.html
./example/hello.jsx
```

**Comment by mpetrovich** [comment]
Great idea @ckrack! This would be very useful.

It may also be useful to have the ability to combine both inline _and_ external examples in cases where you still want some of the code blocks to be inline but want to externalize other ones (eg. common data/code).

### Spec
The form for referencing an external code block could be:
~~~
```<name>:<path>
```
~~~
Where:
- `<name>` is the example name (without file extension)
- `<path>` is the filepath, by default relative to the current file unless explicitly absolute by prefixing with `/`

### Example
~~~markdown
This first example uses a 'data' object from a shared JS file:
```example-1.js
console.log('Example 1: ' + data);
```
```example-1:/path/to/data/data.js
```

This second example uses the same shared JS file:
```example-2.js
console.log('Example 2: ' + data);
```
```example-2:/path/to/data/data.js
```
~~~
Where `/path/to/data/data.js` contains:
```js
data = { … }
```

### Wildcards
Given the following files:
```
// in /path/to/data/data.js:
data = { … }

// in /path/to/somewhere/foo.html:
Data: <div id="data"></div>

// in /path/to/somewhere/bar.js:
document.getElementById('data').innerHTML = JSON.stringify(data);
```

you could write:
~~~markdown
```example-3:/path/to/data/data.js
```
```example-3:/path/to/somewhere/*
```
~~~
which would be equivalent to this inline version:
~~~markdown
```example-3.js
data = { … }
```
```example-3.html
Data: <div id="data"></div>
```
```example-3.js
document.getElementById('data').innerHTML = JSON.stringify(data);
```
~~~

Would this implementation be useful?

**Comment by mpetrovich** [comment]
This feature has been added in [v0.6.0](https://github.com/nextbigsoundinc/stylemark/releases/tag/v0.6.0)
