### ISSUE TITLE
Styles included from external path are not included in the component shadow root document

### ISSUE THREAD

**Issue by kboom** [nextbigsoundinc/stylemark#33]
The library defines an option to include external resources (outside MD file):

`something:relative.css`
or
`something:/absolute.css`

In either case the style won't get included so the component remains unstyled.
I would opt for being able to include styles from external files because this would enable real modular docs

```
component1/
   - dist/bundle.css
   - source.scss
   - readme.md
component2/
   - dist/bundle.css
   - source.scss
   - readme.md

```

Obviously you could include the master style, an outcome of processing all styles but if there are many components with complicated styles you end up having to recompile everything which takes time every time you do a small change in pretty independent component. Normally you would just rebuild the component and load its own bundle.

**Comment by mpetrovich** [comment]
@kboom If I understand what you're asking, this should already work. Any external CSS files (or any other files, for that matter) that you reference _will_ get included and applied to that example.

Let's say you have a `foo` component in a directory with its own Markdown docs and bundled CSS:
```
components/
           foo/
               readme.md
               dist/
                    bundle.css
```

With this `readme.md`:
~~~
---
name: Foo
---

Foo component.

```foo.html
<my-foo>Hello, world</my-foo>
```
```foo:dist/bundle.css
```
~~~
Stylemark _will_ indeed load and apply the styles from `dist/bundle.css` to the `foo.html` example.

Here's the code that demonstrates this in action: https://github.com/mpetrovich/stylemark-issue-33

**Comment by mpetrovich** [comment]
Please reopen if you still have issues. Thanks!
