### ISSUE TITLE
Add option to provide global wrapper for each component example

### ISSUE THREAD

**Issue by kboom** [nextbigsoundinc/stylemark#34]
It would be great to have a wrapper for each of the example files.
So if you define an example like this;

~~~
```example.html
<div class="hello">a</div>
```
~~~

and some option like
~~~
componentWrapper: "<div class="wrapper">{content}</div>"
~~~
you would get

```
<div class="wrapper">
<div class="hello">a</div>
</div>
```

in a final example file.

That is very useful for testing - this library works great with backstopjs (you can use example files directly as url in backstop) but if you have a hover shadow it won't get captured. Surrounding div would be great as it could generalize this so you don't even have to encode class selectors anywhere - provide global instead.

**Comment by mpetrovich** [comment]
Added in [v3.0.0](https://github.com/nextbigsoundinc/stylemark/releases/tag/v3.0.0)
