### ISSUE TITLE
Ability to Add Stylesheet to Load After Stylemark Default Styles, Custom Styleguide Styles (Feature Request)

### ISSUE THREAD

**Issue by davidbwaters** [nextbigsoundinc/stylemark#35]
Hi, I would love to be able to have the ability to specify a custom stylesheet to load after the default Stylemark styles.  I love the cleanliness of the default look, but the ability to tweak and extend it to compliment the design of what we are documenting would be a great option for designers.  

This could be taken even further with a boolean (include default stylesheet) or another optional field (stylesheet to be used in place of default) that would let us use our own stylesheet to completely style the guide interface.

This approach would keep the lean appeal of Stylemark, as opposed to the bloat of adding custom templates/themes other generators have.  I think the ability to use our own styles the default guide markup would add appeal to designers and would let Stylemark users differentiate their docs from other users.

Would love to hear from others' thoughts and ideas on this.  Thanks.

**Comment by mpetrovich** [comment]
We really want to add this and it will happen soon! It's not difficult but will require us to clean up the sidebar and shell HTML so that you'll have clean, easy hooks for styling. (The current HTML is a bit of a mess)

**Comment by mpetrovich** [comment]
Added in [v2.0.0](https://github.com/nextbigsoundinc/stylemark/releases/tag/v2.0.0)

Sorry for the delay!
