### ISSUE TITLE
Add in an option to prevent html markup from showing up

### ISSUE THREAD

**Issue by nickimola** [nextbigsoundinc/stylemark#43]
It would be nice to have an option to allow (default) or dis-allow the HTML accordion from being displayed.

There could be multiple reasons why somebody would like not to show the HTML, for instance, if they are showing off colours; the way I tackled this at the moment is that I've included a class that shows some dots with the background being the colours I want to show, but this HTML markup should really be displayed on the page, as there's nothing helpful there.

Another example could be headings - You want to show the style of the heading but there's no real markup needed in there

I'm trying to add my custom javascript to handle this, but it would be nice to add this feature in my opinion.

Thanks

**Comment by mpetrovich** [comment]
Unless I'm misunderstanding your request, you can achieve this by using the `hidden` flag for the blocks you want to hide the source of. Perhaps we should make that more obvious in [the documentation](https://github.com/nextbigsoundinc/stylemark/blob/master/README-SPEC.md#example-2).

Usage:
~~~
```example.html hidden
...
```
~~~

Example:
~~~
---
name: Sample
---

Sample component.

```sample.html hidden
<p>Hello, world.</p>
```
```sample.css hidden
p {
  color: green;
}
```
~~~

Will show the rendered example with none of the source code visible:
<img width="385" alt="screenshot 2018-06-12 05 26 09" src="https://user-images.githubusercontent.com/1235062/41282071-24db374c-6e01-11e8-974c-c63783001fb9.png">

**Comment by nickimola** [comment]
Yep, that's the one.
Thanks
