### ISSUE TITLE
Performance is slow

### ISSUE THREAD

**Issue by Dobby89** [nextbigsoundinc/stylemark#44]
If I run stylemark in watch mode using `-w` I find that it eventually slows down and becomes unusable. It takes ages to refresh/rebuild and everything starts to lag. Is there something which can be done to improve the performance of the build?

**Comment by mpetrovich** [comment]
Which version are you on?

**Comment by Dobby89** [comment]
@mpetrovich 3.0.1

**Comment by mpetrovich** [comment]
@Dobby89 could you share your stylemark config and your source code directory structure? It may help diagnose the issue.

**Comment by Dobby89** [comment]
Sorry for the delay.

**stylemark.config.yml**
```stylemark.config.yml

assets:
  - ./build
  - ./src/public/fonts
  - ./src/public/images
  - ./src/public/style

theme:
  css:
    - ./src/public/style/stylemark.css
  logo: ./src/public/images/logo.png
  sidebar:
      background: "#7fba23"
      textColor: "#ffffff"

examples:
    css:
      - build/main.css
      - src/public/style/fonts.css
      - src/public/style/demo.css
    bodyHtml: |
      <div class="sg-example">
          {html}
      </div>

order:
  - +Getting Started
  - +General
  - +Objects
```

**File structure**
```
+---build
\---src
    +---framework
    |   +---1_settings
    |   +---2_tools
    |   +---3_generic
    |   +---4_elements
    |   +---5_objects
    |   +---6_components
    |   \---7_utilities
    +---public
    |   +---fonts
    |   +---images
    |   +---style
    \---stylemark
            breadcrumbs.md
            buttons.md
            form-fields.md
            icons.md
            installation.md
            objects-grid.md
            objects-page-wrapper.md
            overview.md
            pagination.md
            panels.md
            setup.md
            typography.md
            utilities.md
package.json
stylemark.config.yml
```

**Comment by mpetrovich** [comment]
I forgot to add: What is the exact stylemark command you’re running?

**Comment by Cyclodex** [comment]
Hi all, I also had big issues with the performance. I forked and tried to improved it a bit for me.
It is a lot more flexible with setting which files you want to watch, both on file(stylemark) and browserSync side. I have nearly no problems now and performance is well.

I created now a PR. Maybe it might help you guys as well:

- #55 
- #56

**Comment by Dobby89** [comment]
@Cyclodex Nice work :)

@mpetrovich Any chance of merging these into Master?

**Comment by mpetrovich** [comment]
Sorry for the delay—we haven't forgotten about this! Due to the holidays here in the US, we haven't had a chance to thoroughly test the changes yet.  Stay tuned!

**Comment by Dobby89** [comment]
@mpetrovich Thanks, I've just updated and it seems a lot faster now,

**Comment by Cyclodex** [comment]
I will check it next 2 weeks hopefully, thanks so far!
