### ISSUE TITLE
Style slightlty broken on select

### ISSUE THREAD

**Issue by nickimola** [nextbigsoundinc/stylemark#45]
This is a minor issue, but the styling of the select box (when on small screens) is slightly broken. Check the attached screenshot.

![capture](https://user-images.githubusercontent.com/9289704/42022069-86397662-7abc-11e8-9076-dabd8b3da6d5.PNG)

Thanks

**Comment by mpetrovich** [comment]
Thanks for reporting! Which OS & browser?

**Comment by nickimola** [comment]
Tested on:
Windows 10 (updated to the latest version)
using Chrome Version 67.0.3396.99 (Official Build) (64-bit)

It might be an issue with the padding bootstrap adds to the select box tho, as removing it completely centres the text.

**Comment by mpetrovich** [comment]
Fixed in [v3.0.2](https://github.com/nextbigsoundinc/stylemark/releases/tag/v3.0.2)
