### ISSUE TITLE
Search is broken on Firefox

### ISSUE THREAD

**Issue by tlhuillier** [nextbigsoundinc/stylemark#49]
Search on Firefox seems to be broken (62.0b15 (64-bit)).

_Searching doesn't do anything:_
![screen shot 2018-08-08 at 18 49 45](https://user-images.githubusercontent.com/25198739/43851800-fe1e90dc-9b3b-11e8-8522-c5009da5c569.png)

_Console error:_
![screen shot 2018-08-08 at 18 46 04 1](https://user-images.githubusercontent.com/25198739/43851813-0649b3b8-9b3c-11e8-9422-50262b695eee.png)

**Comment by mpetrovich** [comment]
Thanks for reporting! We'll fix it this week.

**Comment by mpetrovich** [comment]
Fixed in [v3.0.3](https://github.com/nextbigsoundinc/stylemark/releases/tag/v3.0.3)
