### ISSUE TITLE
Missing configuration file

### ISSUE THREAD

**Issue by Yugloocamai** [nextbigsoundinc/stylemark#51]
Stylemark is asking me for a configuration file, even though the docs claim that -c is optional.

 stylemark -i ./sass -o ./sass-documentation -w 2000 -b 8050
 
 Generating style guide...
 Missing configuration file

**Comment by Yugloocamai** [comment]
ok, even providing a configuration file, and adding -c generates the same error.

**Comment by mpetrovich** [comment]
1. What does your file directory structure look like? (including the location of the configuration file)
2. What is the exact command you're running when you include `-c`?

**Comment by mpetrovich** [comment]
Is your `.stylemark.yml` file within the _input_ directory? `sass` in this case.

Per [the docs](https://github.com/nextbigsoundinc/stylemark#on-the-command-line):
> `configPath ` defaults to .stylemark.yml *within the input directory*

I'll admit that this a surprising default and is starting to make less sense over time.

To fix your issue, either move `.stylemark.yml` to the `sass` directory or explicitly include the config filepath `-c ./.stylemark.yml`. Please reopen if neither of those fix your issue.
