### ISSUE TITLE
Custom sidebar styling

### ISSUE THREAD

**Issue by mpetrovich** [nextbigsoundinc/stylemark#6]
It would be useful to control more of the sidebar styling such as logo placement/dimensions, typography, etc.

**Comment by gethinoakes** [comment]
👍  for this

**Comment by gethinoakes** [comment]
Would the simplest way be to allow us to include our own stylesheet in the head of the generated styleguide?

**Comment by ghaiat** [comment]
Hello, any update about this? Cheers

**Comment by davidbwaters** [comment]
+1 for this.  I've opened a separate issue [here](https://github.com/nextbigsoundinc/stylemark/issues/35) as a feature request for the ability to specify a custom stylesheet to load after the default Stylemark styles.  Feel free to share thoughts and contribute.  Thanks.

**Comment by mpetrovich** [comment]
Added in [v2.0.0](https://github.com/nextbigsoundinc/stylemark/releases/tag/v2.0.0)

Sorry for the delay!
