### ISSUE TITLE
Generator adds empty line if height option is not used in example

### ISSUE THREAD

**Issue by jussikinnula** [nextbigsoundinc/stylemark#60]
Parser creates `<example ...> ... </example>` from the code parts in markdown files. If there's height option, the example contains also it. On generator, the example tag is changed to an iframe.

The problem is, if height is not set - iframe has an extra line break, which breaks some browsers.

**Comment by mpetrovich** [comment]
Fixed in [v3.1.3](https://github.com/nextbigsoundinc/stylemark/releases/tag/v3.1.3)
