### ISSUE TITLE
Search/filter functionality

### ISSUE THREAD

**Issue by ay13** [nextbigsoundinc/stylemark#9]
I don't believe the search functionality works.

Using the demo at http://stylemark-bootstrap.surge.sh/ I type `dropdown` into the search box and hit return. 

The page reloads with the URL http://stylemark-bootstrap.surge.sh/?filter=dropdown but nothing is different. The full page is loaded and at the top of the page.

Am I missing something?

**Comment by mpetrovich** [comment]
Hey @ay13, the search filter in the sidebar is a live type-to-search that doesn't require you to press `ENTER`, but it looks like pressing `ENTER` refreshes the page when it shouldn't. Until that's fix, just avoid pressing `ENTER` after typing your search query.

**Comment by mpetrovich** [comment]
Fixed in v0.6.7
